### ISSUE TITLE
JSON as input?

### ISSUE THREAD

**Issue by fdinkler-mbx** [techjoomla/com_api#116]
Excellent component, have multiple endpoints up and working with token.
Would like to use JSON instead of form for POST input.  
Have experimented, but nothing working yet. 
Hints?

**Comment by manojLondhe** [comment]
Hello,

If your API consumer is posting JSON data correctly, it is possible to get JSON data inside com_api plugin's resources using Joomla's JInput API

Refer
https://docs.joomla.org/Retrieving_request_data_using_JInput#Getting_JSON_string_from_request

**Comment by manojLondhe** [comment]
Closing this.
