### ISSUE TITLE
Warning:   Trying to get property of non-object in /components/com_api/libraries/plugin.php on line 59

### ISSUE THREAD

**Issue by brunobasto** [techjoomla/com_api#15]
Is anyone else getting this warning?

**Comment by coolbung** [comment]
Haven't seen it, but should not be hard to fix since its a warning. You can fix the warning by adding a type check on that line. 

If you're unable to do that you can turn off error reporting and move on with your work.. I'll have it fixed when we next make changes on the API framework

**Comment by brunobasto** [comment]
Thanks! I managed to fix. Just wanted to give you a heads up. It may break your web service output if your server spits out the warning messages.
