### ISSUE TITLE
Replace domain by IP filter for tokens

### ISSUE THREAD

**Issue by eshiol** [techjoomla/com_api#19]
If you set the domain field for an api key, you can call a function with any domain, even empty domain.

**Comment by coolbung** [comment]
I'd vote to remove the domain feature itself, I dont think it makes sense anymore. We should rather add a configuration that lets a user specify the IP addresses that an API key can be used from.

**Comment by eshiol** [comment]
I agree.

**Comment by coolbung** [comment]
Added #62 for IP based restriction. Closing this.
