### ISSUE TITLE
Cant get the Com_api to work

### ISSUE THREAD

**Issue by saisworld** [techjoomla/com_api#24]
Hi,

I installed com_api and users plugin on my Joomla 2.5 website. I downloaded the zip file from github and installed by logging in as admin and installed it via extensions, add new. It installed the Module and Plugin (users). However when I try to access - http://mywebsite.com/index.php?option=com_api&app=users&format=raw&resource=login , it gives me 500 internal server error. Could someone please advise?

Thanks in advance

**Comment by coolbung** [comment]
If it's giving a 500 error, it's likely that you are getting a PHP fatal
error. Can you turn on error reporting and see what error do you get ?

On Sun, May 1, 2016 at 3:18 AM, saisworld <notifications@github.com> wrote:

> Hi,
>
> I installed com_api and users plugin on my Joomla 2.5 website. I
> downloaded the zip file from github and installed by logging in as admin
> and installed it via extensions, add new. It installed the Module and
> Plugin (users). However when I try to access -
> http://mywebsite.com/index.php?option=com_api&app=users&format=raw&resource=login
> , it gives me 500 internal server error. Could someone please advise?
>
> Thanks in advance
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/techjoomla/com_api/issues/24>
>



-- 
Thanks!
Ashwin Date
techjoomla.com
<http://techjoomla.com/?utm_source=email_signature&utm_medium=email&utm_campaign=ashwin>
| appcarvers.com
<http://appcarvers.com/?utm_source=email_signature&utm_medium=email&utm_campaign=ashwin>
| tekdi.net
<http://tekdi.net/?utm_source=email_signature&utm_medium=email&utm_campaign=ashwin>
@coolbung | @techjoomla | @appcarvers | @tekdinet

If it isn't broken, don't fix it!

**Comment by ServeTT** [comment]
Hello.
Have the same problem with articles and categories plugin. Joomla 2.5.28
500 error, in my error_log
PHP Fatal error:  include() [<a href='function.include'>function.include</a>]: Cannot redeclare class jdispatcher in /home/s/servett/grandsmetanew/public_html/libraries/loader.php on line 354

Can You help, please??

**Comment by ServeTT** [comment]
Installed version 1.5.1
https://techjoomla.com/index.php?option=com_ars&amp;view=Items&amp;release_id=268&amp;Itemid=390

Now component works, but result is - API Plugin Not Found

**Comment by coolbung** [comment]
Please check the docs @ServeTT - http://techjoomla.github.io/com_api/

You need to ensure you are calling the right resource URL. With v2.1 you can use SEF URLs. The URL for all articles is 

`/api/articles/article` - list of articles
`/api/articles/article/{id}` - specific article
`/api/categories/categories` - list of content categories

Please check and let me know if you are still facing issues making a call.

**Comment by coolbung** [comment]
Closing. Please reopen with more details if there is still an issue.
