### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by mike-diamond** [techjoomla/com_api#26]
I have installed com api and users plugin.
I try to connect:
mydomain/index.php?option=com_api&app=users&format=raw&resource=loginkey=f501d684ccf92abba4e34cff53e82eee

But browser respond: could not get any respond
Request log is empty. 
Apache2 log: http://prntscr.com/bq1ytu
Error after switching on Debug: Fatal error: Cannot redeclare class JDispatcher in mydomain\libraries\joomla\event\dispatcher.php on line 281
Please help me to connect correctly.

UPD:
When I change the com_api/libraries/plugin.php:58
            //$dispatcher = JEventDispatcher::getInstance();
            $dispatcher = JDispatcher::getInstance();
I see response in browser:
{"code":400,"message":"Users API Plugin not found, Users is probably not installed"}

**Comment by mike-diamond** [comment]
Problem solved only after upgrading to joomla 3

**Comment by coolbung** [comment]
Glad you got it solved. The extension is no more tested with 2.5 so yes
upgrading to 3.x is suggested.

On Fri, Jul 8, 2016 at 5:15 PM, mike-diamond <notifications@github.com>
wrote:

> Problem solved only after upgrading to joomla 3
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/techjoomla/com_api/issues/26#issuecomment-231339998>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAaNM2sZcECS3OBgL_tomiU7ix_NPdWVks5qTjhzgaJpZM4JHUn9>
> .
>



-- 
Thanks!
Ashwin Date
techjoomla.com
<http://techjoomla.com/?utm_source=email_signature&utm_medium=email&utm_campaign=ashwin>
| appcarvers.com
<http://appcarvers.com/?utm_source=email_signature&utm_medium=email&utm_campaign=ashwin>
| tekdi.net
<http://tekdi.net/?utm_source=email_signature&utm_medium=email&utm_campaign=ashwin>
@coolbung | @techjoomla | @appcarvers | @tekdinet

If it isn't broken, don't fix it!
