### ISSUE TITLE
 Notice: Trying to get property of non-object Error

### ISSUE THREAD

**Issue by karthikvijayaveni** [techjoomla/com_api#37]
**I got Following Error** 

 Notice: Trying to get property of non-object in /var/www/joomla/components/com_api/libraries/plugin.php on line 61

I using Joomla 3.6.4 Version

**When I deactive User Plugin get following :+1:** 

Notice: Trying to get property of non-object in /var/www/joomla/components/com_api/libraries/plugin.php on line 61
[{"id":"209","name":"employer","username":"jsjobs_employer","email":"employer@info.com","block":"0","sendEmail":"0","registerDate":"2016-09-20 12:04:58","lastvisitDate":"0000-00-00 00:00:00","activation":"","params":"{\"admin_style\":\"\",\"admin_language\":\"\",\"language\":\"\",\"editor\":\"\",\"helpsite\":\"\",\"timezone\":\"\"}","lastResetTime":"0000-00-00 00:00:00","resetCount":"0","otpKey":"","otep":"","requireReset":"0","group_count":"1","group_names":"Registered","note_count":0},{"id":"211","name":"hghjsgfhjdsfdhsj ghjdfhjsdfhjsdfdsj","username":"sjfhsdhfjsd@sfsdfsd.com","email":"sjfhsdhfjsd@sfsdfsd.com","block":"0","sendEmail":"0","registerDate":"2016-11-09 08:34:48","lastvisitDate":"2016-11-09 08:34:48","activation":"","params":"{}","lastResetTime":"0000-00-00 00:00:00","resetCount":"0","otpKey":"","otep":"","requireReset":"0","group_count":"1","group_names":"Registered","note_count":0},......

**When i active User Plugin get following :+1:** 

{"code":400,"message":"Users API Plugin not found, Users is probably not installed"}

**Comment by coolbung** [comment]
Not seen in v2.0.0 on Joomla 3.7.0 on PHP7.0.21
