### ISSUE TITLE
Articles API Plugin not found, Articles is probably not installed

### ISSUE THREAD

**Issue by boomsya** [techjoomla/com_api#39]
file: \com_api_v1.6.2 (1)\site\libraries\plugin.php

line:
$plgfile	= JPATH_BASE.self::$plg_path.$name.'/'.$name.'.php';

die ($plgfile) => /var/www/html/plugins/api/articles/articles/articles.php

problem: file "articles/articles/articles.php" not found

right path is:
$plgfile	= JPATH_BASE.self::$plg_path.$name.'.php';

and all works with fix

**Comment by OzWolfye** [comment]
Yes thank you - just spent an hour figuring out the above myself. Thought I was going mad but I came to the same conclusion.

**Comment by coolbung** [comment]
The right URL will be `index.php?option=com_api&app=articles&resource=article` I am able to use this URL to list the articles.

**Comment by learneradarsh** [comment]
@coolbung  I think index.php?option=com_api&app=articles&resource=article this url redirects to articles page only are you getting json by using above URL?
