### ISSUE TITLE
where is jomsocial api plugin?

### ISSUE THREAD

**Issue by smoore5527** [techjoomla/com_api#41]
What happened to the jomsocial api plugin? the website said it was already available on github?

**Comment by coolbung** [comment]
Where do you see it mentioned. Currently there is no Jomsocial plugin, unfortunately.

**Comment by smoore5527** [comment]
its on techjoomlas website.

https://techjoomla.com/free-downloads/rest-api-for-joomla.html

The Latest version of com_api supports Joomal 2.5 & Joomla 3.0.  Get it here on GitHub.
API plugins are available for many extensions including Joomla content, Users, JomSocial, SOBI, AEC, SocialAds to name a few. Get them here on GitHub .
If you are interested in the older XMLRPC like separate application version, you can get it here. Note that we don't maintain that anymore.

**Comment by coolbung** [comment]
That was a problem with the documentation unfortunately, we have corrected the docs. 

There is no Jomsocial plugin as of now. However you can refer the docs to write any kind of plugins - http://docs.techjoomla.com/category/joomla-rest-api
