### ISSUE TITLE
Enable CORS Support

### ISSUE THREAD

**Issue by coolbung** [techjoomla/com_api#54]
Implement CORS support for com_api in the following way

Create 2 config options 
- Enable CORS 
This will be a radio with options as GET, POST and All

- CORS domains
This will be a textarea that accepts one domain per line

Based on the values of these configurations, the CORS headers are set. If the config is set to POST, then com_api should also be able to respond to a pre-flight OPTIONS request with the right headers. 

The following CORS headers need to be set based on the following flowchart - 
https://www.html5rocks.com/static/images/cors_server_flowchart.png

**Comment by coolbung** [comment]
Also set the `Access-Control-Allow-Headers` value should be Authorization, Access-Control-Allow-Origin, Access-Control-Allow-Methods, X-Authorization, X-Compatibility-Mode, Content-Type, Accept

**Comment by coolbung** [comment]
@thite-amol in the config section create a new tab CORS and move the existing 2 options there. Also add the above as a third option with comma separated list of headers in a textarea.

**Comment by sushan05** [comment]
@thite-amol - Faced an issue while calling the API if multiple domains (separated by comma) are provided in "Allow Cross Origin Requests" field. The error message is as follows- 

XMLHttpRequest cannot load http://staging.xyz.com/index.php?option=com_api&app=external&resource=homepage&format=raw.
The 'Access-Control-Allow-Origin' header contains multiple values 'http://client-xyz.host/, http://yahoo.com, http://google.com', but only one is allowed. Origin 'http://client-xyz.host' is therefore not allowed access.

**Comment by coolbung** [comment]
Good find Sushan !

Let's use all the above comments to have a really solid CORS implementation

**Comment by thite-amol** [comment]
This feature is implemented in the latest package so closing it from here.
