### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by efstathiosntonas** [techjoomla/com_api#56]
Does the extension supports pagination? I want to implement infinite scroll in my mobile app.

If yes, how it's impemented?

Thanks

**Comment by coolbung** [comment]
Hi Efstathios,

The com_api component is really a framework to build API plugins that allow you expose parts of your component as APIs. 

The limit / pagination will need to be implemented by the plugin itself. You can refer the Joomla article plugin to see how pagination is implemented - 
https://github.com/techjoomla/com_api-plugins/blob/master/articles/articles/article.php#L75

**Comment by coolbung** [comment]
Closing this issue. Please reopen with more details if you face any problems.
