### ISSUE TITLE
CORS issue for POST method call when CORS is set with domains name / names

### ISSUE THREAD

**Issue by sushan05** [techjoomla/com_api#65]
## Steps to reproduce - 

- Set **Allow Cross Origin Requests** to **All**
- Set **CORS URLs / Domains** to a particular site where you are consuming API's.
- Now hit the POST API.

You will get the below error in console.
_- Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xyz.com' is therefore not allowed access._

**Comment by thite-amol** [comment]
I have tested this issue with the latest package and working fine for me with multiple domains. If you face issue with please add steps to reproduce it.
