### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by amitdangwal** [techjoomla/com_api#72]
Hi,

I tried to install the com_api and the default user plugin. I got the error as HTTP ERROR 500 when I tried to open the url
https://xyz.com/index.php?option=com_api&app=users&format=raw&resource=users&key=mykey

There is nothing recorded on error_log so I am not able to catch the error. Server is using php 5.4, cent OS.
I guess somewhere issue in with http.php but it is a guess only as it seem this file is not loading 
api.php
if (file_exists($c_path))
{
	include_once $c_path;
	$c_name = 'ApiController' . ucwords($c);
}

file do exists with full permission. Please share any hint as what could be wrong.

joomla error log, php error log all set to maximum. still not recording error but giving blank page(not 500 which was appearing before)

**Comment by coolbung** [comment]
We haven't tested on PHP 5.4. You should upgrade to PHP 7.

**Comment by amitdangwal** [comment]
Thank you. Yes it is issue with version. I have tried it on php 5.6 and it started to work. Sadly I cannot change production php version to higher as there are number of integration apps which are bombarding if I change production php version. I will be using com_api but at moment not sure if I should try making it compatible with 5.4 (not sure if it is possible too or too much of work)

**Comment by coolbung** [comment]
PHP 5.4 is a very old version. I suggest you should take the pains to upgrade. 

You may figure out the effort to back-port to PHP 5.4 but I wouldn't recommend that.

**Comment by amitdangwal** [comment]
Thank you for your inputs. I highly appreciate it.  I will see if I can go for 5.6

**Comment by coolbung** [comment]
Alright. Closing the issue.
