### ISSUE TITLE
Trusted IP

### ISSUE THREAD

**Issue by amitdangwal** [techjoomla/com_api#73]
Hi Team,

Is there any default option for adding trusted IP. I wanted to restrict API Key access only from a trusted IP so that data is protected even if key is compromised. There will be chances that any user in team intensionally/unintentionally share key with any non-authorized user. So if request is coming from only trusted IP then allow else not. I understand that it does not guarantee data protection fully but still it is  kind of additional level of protection.

If this feature is there then please guide otherwise I will add this through customization.

Thanks,
Amit

**Comment by coolbung** [comment]
Hi. This feature is currently not available. How it's already in the backlog -

https://github.com/techjoomla/com_api/issues/62

So if you will be building this feature, I'll be happy to help you out and accept your pull request to integrate this feature into the core of com_api.

I'm closing this issue as a duplicate, please share your progress on the other issue. You don't need to implement everything mentioned in that issue. You can start simple by adding IP based restrictions.
