### ISSUE TITLE
Which version of joomla com_api supports?

### ISSUE THREAD

**Issue by zhilevan** [techjoomla/com_api#76]
After looking on your Documentation I haven't found anything about compatible version which com_api version support, I tried (from https://extensions.joomla.org/extension/rest-api/)  com_api_v1.5.1.zip, com_api_v1.6.2.zip , com_api_v2.2.zip versions 
but in all faced with **Error! Could not find a Joomla! XML setup file in the package**

**which version of Joomla com_api support ? I want to have it in joomla 1.5, what is your suggestion?**

**Comment by coolbung** [comment]
Joomla 1.5 is not supported anymore, it's a version more than 6 years old :) You should consider upgrading to the latest Joomla 3.x release. com_api works with that.

If you really need the older version, you can get the code [here](https://github.com/techjoomla/com_api/tree/1.5). However note that you'll be on your own in terms of creating a package and troubleshooting if there are any issues. Also, I don't think there are a lot of plugins for the older version.

**Comment by zhilevan** [comment]
Thank you for replying, I'm aware of it Joomla 1.5 is very old and also there is a lot of security issued about it, but my friend's website is based on it and at this time we don't have much time to upgrade it.

I just need a plugin which return the content in json (some content), for feed our mobile application .

**Comment by coolbung** [comment]
Sure. You can use the Joomla 1.5 version and create a new plugin for that. The 1.5 branch also has some plugins that you can refer to write your own plugin.
