### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by raramuridesign** [techjoomla/com_api#8]
Joomla 3.3.6
com_api, latest version

After installing the latest version the following error occurs

An error has occurred.
 0 Unknown column 'a.checked_out' in 'on clause' SQL=SELECT COUNT(_) FROM `jir57_api_keys` AS a LEFT JOIN jir57_users AS uc ON uc.id=a.checked_out LEFT JOIN jir57_users AS userid ON userid.id = a.userid LEFT JOIN jir57_users AS created_by ON created_by.id = a.created_by Unknown column 'a.checked_out' in 'on clause' SQL=SELECT DISTINCT a._,uc.name AS editor,userid.name AS userid,created_by.name AS created_by FROM `jir57_api_keys` AS a LEFT JOIN jir57_users AS uc ON uc.id=a.checked_out LEFT JOIN jir57_users AS userid ON userid.id = a.userid LEFT JOIN jir57_users AS created_by ON created_by.id = a.created_by ORDER BY a.id asc LIMIT 0, 20 Unknown column 'a.checked_out' in 'on clause' SQL=SELECT COUNT(*) FROM `jir57_api_keys` AS a LEFT JOIN jir57_users AS uc ON uc.id=a.checked_out LEFT JOIN jir57_users AS userid ON userid.id = a.userid LEFT JOIN jir57_users AS created_by ON created_by.id = a.created_by

**Comment by coolbung** [comment]
The users plugin is working without an issue. Please share the request headers & body to be able to debug. Also ensure that you upgrade to the latest versions of the extension and plugins before testing again.

Closing this issue. Please reopen with more details if you face any problems.
