### ISSUE TITLE
Save and show request method in logs

### ISSUE THREAD

**Issue by coolbung** [techjoomla/com_api#81]
Currently the request method is not visible in the logs. This should be saved in the DB and displayed on the logs page.

**Comment by niteshkesarkar** [comment]
- As per my knowledge following are the steps to do what you said. Please let me know if anything I missed. Also, suggest any better solution available. Need some setup related help to install and test with some of the API plugins. Whom should I connect with? - @manojLondhe @coolbung @Pratikshakhandagale 

Implementation Steps:

- Adding a new file at the following location and the code
`administrator\components\com_api\sql\updates\mysql\2.5.2.sql`
>       ALTER TABLE "#__api_logs" ADD "request_method" varchar(20) NOT NULL DEFAULT '';
- Add column name to sorting filter (`function - getSortFields`) at following location
`administrator\components\com_api\views\logs\view.html.php`
>       'a.request_method' => JText::_('COM_API_LOGS_REQUEST_METHOD')
- Add language constants at the following locations
`administrator\language\en-GB\en-GB.com_api.ini`
`administrator\components\com_api\language\en-GB\en-GB.com_api.ini`
>      COM_API_LOGS_REQUEST_METHOD="Request Method"
- Add a column and its value in the list view at the following location
`administrator\components\com_api\views\logs\tmpl\default.php`
>      echo JText::_('COM_API_LOGS_REQUEST_METHOD');
>      echo $item->request_method;
- Add the request_method in bind function of following location
`administrator\components\com_api\tables\log.php`

>       $array['request_method'] = $_SERVER['REQUEST_METHOD'];

**Comment by manojLondhe** [comment]
>    $array['request_method'] = $_SERVER['REQUEST_METHOD'];

@niteshkesarkar 
Looks OK, ensure to use Joomla's input class instead of using superglobals directly.

Connect with @thite-amol for more details if needed

**Comment by manojLondhe** [comment]
Closed in https://github.com/techjoomla/com_api/pull/112
