### ISSUE TITLE
/api/user/login API 

### ISSUE THREAD

**Issue by radomirradojevic** [techjoomla/com_api#84]
Hi 
Could you explain this in more depth please 

**Documentation says:**
key / token
**It’s also possible to use the /api/user/login API to login using username and password and get a token in response.**

Should I create plugin **user** and public resource **login** that accepts username and password with simple logic that checks user credentials and then inserts userid and hash (key) in table #__api_keys?

**Comment by coolbung** [comment]
Hi

The user plugin already has a login resource that does this for you. You should make a POST call to `/api/users/login` and send the username and password. In case of successful login, the API will respond with the token that can be used for subsequent API calls.
