### ISSUE TITLE
Logs user out in Joomla 3.9.X

### ISSUE THREAD

**Issue by grantg182** [techjoomla/com_api#94]
I have been using com_api successfully for the best part of 2 years. It has worked perfectly well for my use case running Joomla 3.6.X. However, upon upgrading to 3.9.1 and then 3.9.2 and now 3.9.3, it has been noticed that when using my custom plugin, which I have stripped down completely to only return a hardcoded string, the user session is still being killed.

I have the plugin set to use setResourceAccess to public.

I am calling the API via an AJAX request, which returns the string. However, the user has already been logged out at before this request is even made.

Anyone have this successfully running in the latest version of Joomla?

**Comment by grantg182** [comment]
Upon further investigation, it appears this is broken from Joomla 3.8 onwards.

In my custom plugin, I have the following basic structure:- /plugins/api/customapi/custom.php:-

class plgAPICustomApi extends ApiPlugin
{
        public function __construct(&$subject, $config = array())
        {
                parent::__construct($subject, $config = array());

                //load helper file
                require_once JPATH_SITE.'/plugins/api/customapi/playlists/helper/simpleschema.php';

                ApiResource::addIncludePath(dirname(__FILE__).'/customapi');

                // Set resources & access
                $this->setResourceAccess('custom', 'public', 'get');
        }
}
/plugins/api/customapi/custom.php:-

class CustomApiApiResourceCustom extends ApiResource
{

        /**
         * get Method to get custom object
         *
         * @return  JSON Object
         *
         * @since  1.0
         */
        public function get()
        {
                $this->plugin->setResponse($this->getCustomObject());
        }

My getCustomObject() function gets some data from the current viewed article. I am calling the custom API from an AJAX request.

I have since discovered that if I create an API key and hardcode this as an Authentication: Bearer header in the AJAX request, that I remain logged in. However, this is of no use - I literally do not care about authentication, whether the user is logged in or not, hence setResourceAccess is set to public.

What is the best way forward? Some, not all, of my "users" will be logged in, but I need the api to return the same data irrespective if they are logged in or not - so do not need nor wish to have to create an API token on the fly for each "user".

**Comment by coolbung** [comment]
If you are sure that you will be using the API calls on the same Joomal site where the user is logged in, then you can set the `X-Auth` header to `session`.

However, usually if it is the same site, you can just create a controller.json.php instead of creating an API plugin.

**Comment by coolbung** [comment]
Closing this, please reopen in case you continue to face issues even with the approach suggested above.
