### ISSUE TITLE
Errors when installing plugins 

### ISSUE THREAD

**Issue by jaspreetsinghmadan** [techjoomla/com_api#99]
Hi,
Apology I have to post this query in this repo issues, as the other repo -  https://github.com/techjoomla/com_api-plugins/issues/93, is not active. I am trying to expose joomla content through REST APIs using com_api. While installing plugins from com_api_plugins, I am getting error - > Call to a member function children() on null. 
Version details
Joomla version - 3.9
php version - 7.0.10.

Can you please help?

**Comment by manojLondhe** [comment]
closing based on the conversation from https://github.com/techjoomla/com_api-plugins/issues/93
